--- #YAML:1.0
name: Graph-Simple
version: 0.05
version_from: lib/Graph/Simple.pm
license: gpl
distribution_type: module
generated_by: Graph-Simple version 0.05
installdirs: site
requires:
  Graph: 0.5
