---
abstract: 'simple and intuitive interface for manipulating graph'
author:
  - 'Alexis Sukrieh <sukria@sukria.net>'
build_requires:
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graph-Simple
requires:
  Carp: 0
  Moo: 0
resources:
  bugtracker: https://github.com/sukria/Graph-Simple/issues
  homepage: https://github.com/sukria/Graph-Simple/wiki
  repository: git://github.com/sukria/Graph-Simple.git
version: 0.04
