#!/usr/bin/perl -w

# Convert an input file containing a Graph::Simple description to
# standalone SVG file

# Example usage:
#  examples/as_svg t/in/2nodes.txt >test.svg

BEGIN
  {
  $|++; # output buffer off
  }

use strict;
use lib 'lib';
use Graph::Simple::Parser;

my $file = shift;

my $parser = Graph::Simple::Parser->new( debug => 0 );
my $graph = $parser->from_file( $file );

die ($parser->error()) unless defined $graph;
$graph->layout();
warn ($graph->error()) if $graph->error();

print $graph->as_svg( { standalone => 1 } );

